name: JSON Validator

on:
  push:
    branches: [ main ]
  pull_request_target:
        types: [ opened, synchronize ]

  workflow_dispatch:

jobs:
  Validatejson:
    name: Validate json
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint constants
        run: |
          #!/bin/bash
          echo "Linting contants..."
          for filename in constants/*.json; do
            if ! python -mjson.tool "$filename" &> /dev/null ; then
                echo "Linting $filename failed:"
                python -mjson.tool "$filename" > /dev/null
            fi
          done
          echo "Linted."